apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-metrics
  namespace: m
  labels:
    release: prometheus  # Обязательно! Prometheus ищет этот label
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  namespaceSelector:
    matchNames:
      - m
  endpoints:
    - port: metrics
      interval: 15s
