apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-postgres
  namespace: hw08
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-postgres
  template:
    metadata:
      labels:
        app: delivery-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "delivery_db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-postgres
  namespace: hw08
spec:
  selector:
    app: delivery-postgres
  ports:
  - port: 5432
