apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: hw08
type: Opaque
stringData:
  DB_USER: "saga_user"
  DB_PASSWORD: "saga_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: hw08
type: Opaque
stringData:
  RABBITMQ_PASSWORD: "saga_rabbit_pass"
