apiVersion: v1
kind: Secret
metadata:
  name: hw07-db-secret
  namespace: hw07
type: Opaque
stringData:
  # Billing Service DB
  BILLING_DB_PASSWORD: "billing_secret_password"
  
  # Notification Service DB
  NOTIFICATION_DB_PASSWORD: "notification_secret_password"
  
  # Order Service DB
  ORDER_DB_PASSWORD: "order_secret_password"
