apiVersion: v1
kind: Secret
metadata:
  name: usercrud-secret
  labels:
    app: usercrud
type: Opaque
stringData:
  # Секретные данные для PostgreSQL
  # В production использовать sealed-secrets или external-secrets
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
